### ISSUE TITLE
make compile-slight-engine blows chunks all over my console: wasi-sdk was not installed at the specified path

### ISSUE THREAD

**Issue by squillace** [danbugs/slightjs#1]
git clone
cd in
then the following. So where do I get the wasi-sdk to install into this path? 

> wasi-sdk not installed in specified path of /home/squillace/.cargo/registry/src/github.com-1ecc6299db9ec823/quickjs-wasm-sys-0.1.2/wasi-sdk

▶ make compile-slight-engine
cargo build --package slightjs-engine --target wasm32-wasi
    Blocking waiting for file lock on build directory
   Compiling libc v0.2.139
   Compiling syn v1.0.109
   Compiling cc v1.0.79
   Compiling once_cell v1.17.1
   Compiling send_wrapper v0.6.0
   Compiling serde v1.0.152
   Compiling anyhow v1.0.69
   Compiling atty v0.2.14
   Compiling clang-sys v1.6.0
   Compiling which v4.4.0
   Compiling env_logger v0.9.3
   Compiling clap v2.34.0
   Compiling serde_derive v1.0.152
   Compiling bindgen v0.59.2
   Compiling quickjs-wasm-sys v0.1.2
error: failed to run custom build command for `quickjs-wasm-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/squillace/work/squillace/slightjs/target/debug/build/quickjs-wasm-sys-575c37e6399e6d97/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'wasi-sdk not installed in specified path of /home/squillace/.cargo/registry/src/github.com-1ecc6299db9ec823/quickjs-wasm-sys-0.1.2/wasi-sdk', /home/squillace/.cargo/registry/src/github.com-1ecc6299db9ec823/quickjs-wasm-sys-0.1.2/build.rs:11:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:3: compile-slight-engine] Error 101

**Comment by danbugs** [comment]
Alright~ I've managed to replicate this. It seems I just forgot doing this, but it's mentioned in the README for `quickjs-wasm-sys`.

To fix, you'll have to install the WASI SDK on your system, like so:

- On Linux:
```
curl -sS -L -O https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-15/wasi-sdk-15.0-linux.tar.gz
tar xf wasi-sdk-15.0-linux.tar.gz
sudo mkdir -p /opt/wasi-sdk
sudo mv wasi-sdk-15.0/* /opt/wasi-sdk/
sudo rm -rf wasi-sdk-*
```

- On MacOS:
```
curl -sS -L -O https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-15/wasi-sdk-15.0-macos.tar.gz
tar xf wasi-sdk-15.0-macos.tar.gz
sudo mkdir -p /opt/wasi-sdk
sudo mv wasi-sdk-15.0/* /opt/wasi-sdk/
sudo rm -rf wasi-sdk-*
chmod +x /opt/wasi-sdk/bin/clang
```

- On Windows:
```
wget -O wasi-sdk-15.0-mingw.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-15/wasi-sdk-15.0-mingw.tar.gz
mkdir -p C:\wasi-sdk
tar -xvzf wasi-sdk-15.0-mingw.tar.gz --strip-components=1 -C C:\wasi-sdk
```

After that, run: `export QUICKJS_WASM_SYS_WASI_SDK_PATH=/opt/wasi-sdk`, and you should be good to go.

> PS You might want to set `export QUICKJS_WASM_SYS_WASI_SDK_PATH=/opt/wasi-sdk` in your `~/.zprofile` and `source` it (if you are on Mac) or something of the sort to avoid having to re-do this step every time.

**Comment by danbugs** [comment]
I think this should be fixed now, so I'm closing the issue~ lemme know if you run into any other problems.
